config/routes.rb
Hedonismbot::Application.routes.draw do
  root to: 'static_pages#index'
  resources :users, except: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :shows, only: [:index]
  resources :trackings, only: [:create, :destroy]
  get '/about' => "static_pages#about", as: "about"
  get '/signup' => "users#new", as: "signup"
  get '/signup' => "sessions#new", as: "login"
  get '/logout' => "sessions#destroy", as: "logout"
  post 'shows/:id/resurrect', to: "shows#resurrect", as: "resurrect"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    current_user ? @user = User.find(current_user.id) : @user = User.new

    @trackings = @user.trackings.includes(:show)

    @demo_shows = [Show.find_by_title("Game of Thrones"), 
      Show.find_by_title("Futurama"),
      Show.find_by_title("Adventure Time"),
      Show.find_by_title("Parks and Recreation"),
      Show.find_by_title("Cosmos: A Space-Time Odyssey"),
      Show.find_by_title("Top Gear")]
  end
end

app/views/static_pages/index.html.haml
.wrapper
  .heading
    %h1#header 
      = precede 'Hedonism' do
        %span.stronger.serif Bot
    %h2#subheader Track TV shows to see when the next episode or season will air.
    #query
      = form_tag(trackings_path, method: :post, remote: true, id: "query_form_tag")  do
        = text_field_tag "show_title", "", { placeholder: "Try now: enter a show title, e.g. \"Homeland\"", autofocus: true, required: "required" }
        = submit_tag nil, { id: 'hidden_submit_button', style: 'display: none;' }
        %span#query_submit
          = render "partials/query_submit_button"
      #errors
  #mid_wrapper
    #mid_links
      - if current_user.nil? || current_user.guest?
        %li= link_to "Signup", '#', {class: 'signup_link'}
        %li= link_to "Login", '#', {id: 'login_link'}
      - else
        %li= link_to "Logout", logout_path
      %li= link_to "About", '#', {id: 'about_link'}
      %li= link_to "Help", '#', {id: 'help_link'}
    #popin
      - flash.each do |name, msg|
        = content_tag :div, msg, class: 'error_block'
      #signup
        = render partial: "partials/signup" 
      #login
        = render partial: "partials/login" 
      #about
        = render partial: "partials/about" 
      #help
        = render partial: "partials/help"
.content
  #shows
    - if @trackings.empty?
      %h2 Sample cards:
      = render partial: "shows/show", collection: @demo_shows
    - else
      = render partial: "trackings/user_shows"
.footer