config/routes.rb
Hedonismbot::Application.routes.draw do
  root to: 'static_pages#index'
  resources :users, except: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :shows, only: [:index]
  resources :trackings, only: [:create, :destroy]
  get '/about' => "static_pages#about", as: "about"
  get '/signup' => "users#new", as: "signup"
  get '/signup' => "sessions#new", as: "login"
  get '/logout' => "sessions#destroy", as: "logout"
  post 'shows/:id/resurrect', to: "shows#resurrect", as: "resurrect"
end

app/views/partials/_about.html.haml
%p#about_blurb
  HedonismBot is a pet project by
  = succeed '.' do
    = link_to "Kevin Ko", "http://www.kokev.in"
  It was built as a tool for hedonistic, voracious consumers of television to keep track of when episode delays occurred or when season openers would premier.
  %br
  %br
  HedonismBot is built with Ruby on Rails and utilizes the 
  = link_to "TVRage", "http://www.tvrage.com"
  and
  = link_to "TVDB", "http://www.thetvdb.com"
  APIs. 
  = link_to "Contact me", "mailto:kevin@kokev.in"
  if you have any questions :).
#youtube
  %iframe{width: "280", height: "190", src: "//www.youtube.com/embed/Sv4Gui9hKCM?rel=0", frameborder: "0"}

app/views/partials/_help.html.haml
%p#help_blurb
  Can't find the correct show?
  %br 
  %li
    Try adding the country, e.g. 
    %span.stronger "Wilfred (US)" 
    instead of 
    %span.stronger "Wilfred"
  %li 
    Try adding any subtitles, e.g. 
    %span.stronger"Cosmos: A Space-Time Odyssey" 
    instead of 
    %span.stronger "Cosmos"
  %li You may get faster/more accurate loading with correct spelling!
  %br
  If you have any other questions, send them to
  = link_to "kevin@kokev.in", "mailto:kevin@kokev.in"

app/views/partials/_login.html.haml
#login_blurb
  Log in to access your shows:
  = form_tag(sessions_path, method: :post) do
    = text_field_tag "email", "", { placeholder: "E-mail" }
    %br
    = password_field_tag "password", "", { placeholder: "Password" }
    %br
    = submit_tag "Log me in!"

app/views/partials/_query_submit_button.html.haml
= link_to "", onclick: "$('#hidden_submit_button').click(); return false" do
  %i.icon-plus-circled

app/views/partials/_signup.html.haml
#signup_blurb
  Sign up to save your shows:
  = form_for :user, :url => {:controller => 'users', :action => 'create'} do |f|
    = f.text_field "email", { placeholder: "E-mail" }
    %br
    = f.password_field "password", { placeholder: "Password" }
    %br
    = f.submit "Sign up!", id: "signup_button"