config/routes.rb
Hedonismbot::Application.routes.draw do
  root to: 'static_pages#index'
  resources :users, except: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :shows, only: [:index]
  resources :trackings, only: [:create, :destroy]
  get '/about' => "static_pages#about", as: "about"
  get '/signup' => "users#new", as: "signup"
  get '/signup' => "sessions#new", as: "login"
  get '/logout' => "sessions#destroy", as: "logout"
  post 'shows/:id/resurrect', to: "shows#resurrect", as: "resurrect"
end

app/models/tracking.rb
class Tracking < ActiveRecord::Base
  belongs_to :user
  belongs_to :show

  attr_accessible :user_id, :show_id
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_filter :load_imperatives, except: [:destroy]

  def create
    @title = params[:show_title]
    @show = Show.find_by_title(@title.titleize)

    if @show
      @tracking = Tracking.create(:user_id => @user.id, :show_id => @show.id)
      render 'success'

    elsif Show.show_available?(@title)
      @canonical_title = Show.show_available?(@title)
      @show            = Show.find_or_initialize_by_title(@canonical_title)

      @show.save if @show.new_record?

      Show.create_show_data(@title, @canonical_title, @show.id) if @show.status.nil?

      @tracking = Tracking.create(:user_id => @user.id, :show_id => @show.id)

      if @tracking.valid?
        render 'success'
      else
        render 'error'
      end

    else
      render 'error'
    end
  end

  def destroy
    @id = params[:id]
    Tracking.find(@id).destroy
    render 'destroy_success'
  end

  private

  def load_imperatives
    # Creates a guest user
    current_user ? @user = User.find(current_user.id) : @user = User.new_guest

    if @user.guest?
      @user.save
      session[:user_id] = @user.id
    end

    @trackings = @user.trackings.includes(:show)
  end
end

app/views/trackings/_tracking.html.haml
%li
  %span.delete
    = link_to tracking_path(tracking), method: :delete, class: "delete_tracking", remote: true do 
      %i.icon-cancel-circled 
  .show_view
    %img{src: tracking.show.banner, width: "420px"}
    .title= tracking.show.title
    - if tracking.show.ended?
      %p.ended Show has ended.
      = link_to "Is this incorrect?", resurrect_path(tracking.show), method: 'post', class: "resurrect_link" 
    - else
      .next
        %p
          %strong
            = precede 'Next Air Date: ' do 
              %span.next_date= date_presenter_for_next_airdate(tracking.show.next_airdate)
          %br
          %span.stronger= tracking.show.next_episode ? "Episode: #{tracking.show.next_episode} - \"#{tracking.show.next_title}\"" : "Episode: N/A"
          %br
          = tracking.show.airtime ? "Air Time: #{tracking.show.airtime}" : "Air Time: N/A"
    .last
      %p
        %span.stronger= "Last Air Date: #{date_presenter_for_last_airdate(tracking.show.last_airdate)}"
        %br
        = tracking.show.last_episode ? "Episode: #{tracking.show.last_episode} - \"#{tracking.show.last_title}\"" : "Episode: N/A"

app/views/trackings/_user_shows.html.haml
%h2 Your Tracked Shows:
%p#logged_in_as
  = "Logged in as #{current_user.name}."
  - if current_user.guest?
    = link_to "Sign up", '#', {id: 'scroll_to_signup', class: 'signup_link'}
    = "to save your shows."
#user_shows    
  = render @trackings

app/views/trackings/destroy_success.js.erb
var cardToRemove = "a.delete_tracking[href='/trackings/" + <%= @id %> + "']"

$(cardToRemove).parent().parent().fadeOut(400);

app/views/trackings/error.js.erb
$('#errors').html("<div class='error_block'>Sorry, something went wrong! Make sure your spelling is correct and try again.</div>");
$('#query_submit').html("<%= escape_javascript(render 'partials/query_submit_button') %>")

app/views/trackings/success.js.erb
$('#shows').html("<%= escape_javascript(render 'trackings/user_shows') %>")
$('#query_submit').html("<%= escape_javascript(render 'partials/query_submit_button') %>")
$('.error_block').html("");
$('.error_block').removeClass();
$('#show_title').val("")